#!/bin/sh

# wrap-for-bin.sh: Template for git executable wrapper scripts
# to run test suite against sandbox, but with only bindir-installed
# executables in PATH.  The Makefile copies this into various
# files in bin-wrappers, substituting
# /home/bob/projects/git3, /home/bob/projects/git3/templates/blt and /home/bob/projects/git3/git3.

GIT_EXEC_PATH='/home/bob/projects/git3'
if test -n "$NO_SET_GIT_TEMPLATE_DIR"
then
	unset GIT_TEMPLATE_DIR
else
	GIT_TEMPLATE_DIR='/home/bob/projects/git3/templates/blt'
	export GIT_TEMPLATE_DIR
fi
MERGE_TOOLS_DIR='/home/bob/projects/git3/mergetools'
GITPERLLIB='/home/bob/projects/git3/perl/build/lib'"${GITPERLLIB:+:$GITPERLLIB}"
GIT_TEXTDOMAINDIR='/home/bob/projects/git3/po/build/locale'
PATH='/home/bob/projects/git3/bin-wrappers:'"$PATH"

export MERGE_TOOLS_DIR GIT_EXEC_PATH GITPERLLIB PATH GIT_TEXTDOMAINDIR

case "$GIT_DEBUGGER" in
'')
	exec "/home/bob/projects/git3/git3" "$@"
	;;
1)
	unset GIT_DEBUGGER
	exec gdb --args "/home/bob/projects/git3/git3" "$@"
	;;
*)
	GIT_DEBUGGER_ARGS="$GIT_DEBUGGER"
	unset GIT_DEBUGGER
	exec ${GIT_DEBUGGER_ARGS} "/home/bob/projects/git3/git3" "$@"
	;;
esac
