name: check-whitespace

# Get the repository with all commits to ensure that we can analyze
# all of the commits contributed via the Pull Request.
# Process `git log --check` output to extract just the check errors.
# Exit with failure upon white-space issues.

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-whitespace:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: git log --check
      id: check_out
      run: |
        problems=()
        commit=
        commitText=
        lastcommit=
        while read dash sha etc
        do
          case "${dash}" in
          "---")
            if test -z "${commit}"
            then
              lastcommit=${sha}
            fi
            commit="${sha}"
            commitText="${sha} ${etc}"
            ;;
          "")
            ;;
          *)
            if test -n "${commit}"
            then
              problems+=("" "--- ${commitText}")
              echo ""
              echo "--- ${commitText}"
              commit=
            fi
            problems+=("${dash} ${sha} ${etc}")
            echo "${problems[-1]}"
            ;;
          esac
        done <<< $(git log --check --pretty=format:"---% h% s" ${{github.event.pull_request.base.sha}}..)

        if test ${#problems[*]} -gt 0
        then
          if test -z "${commit}"
          then
            lastcommit=${{github.event.pull_request.base.sha}}
          fi
          echo "A whitespace issue was found in one or more of the commits." >$GITHUB_STEP_SUMMARY
          echo "" >>$GITHUB_STEP_SUMMARY
          echo "Run \`git rebase --whitespace=fix ${lastcommit}\` and \`git push --force\` to correct the problem." >>$GITHUB_STEP_SUMMARY
          for i in "${problems[@]}"
          do
            echo "${i}" >>$GITHUB_STEP_SUMMARY
          done

          exit 2
        fi
